repos:
  # Conventional Commits hook to enforce commit message standards
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [feat, fix, ci, chore, test] # optional: list of Conventional Commits types to allow

  # Python linter and fixer
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.6
    hooks:
      - id: ruff
        stages: [commit]
        args: [--fix]

  # Python import sorter
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        stages: [commit]

  # Python code formatter
  - repo: https://github.com/psf/black
    rev: 24.4.0
    hooks:
      - id: black
        stages: [commit]

  # General purpose pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # Hook to check for merge conflict markers
      - id: check-merge-conflict
        stages: [commit]

      # Hook to check for trailing whitespace
      - id: trailing-whitespace
        stages: [commit]

      # Hook to ensure files end with a newline
      - id: end-of-file-fixer
        stages: [commit]
