services:
# Infrastructure Services
  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
    volumes:
      - ./src/configs/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - competition-api
      - public-api
      - admin-panel
      - public-website
      - grafana
      - keycloak
      - minio
      - prometheus
      - loki

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-guest}

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: taca_ua
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.0
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HTTP_RELATIVE_PATH: /keycloak
      KC_PROXY_HEADERS: xforwarded

# Observability
  prometheus:
    image: prom/prometheus:v2.45.0
    volumes:
      - ./src/configs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  loki:
    image: grafana/loki:2.8.2
    volumes:
      - ./src/configs/loki/loki-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml

  grafana:
    image: grafana/grafana:10.0.0
    volumes:
      - ./src/configs/grafana/provisioning:/etc/grafana/provisioning
      - ./src/configs/grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3002:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
      - loki

# APIs
  competition-api:
    build:
      context: ./src/apis/competiotion-api
      dockerfile: Dockerfile
    volumes:
      - ./src/apis/competiotion-api:/app
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=${RABBITMQ_USER:-guest}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD:-guest}
      - DATABASE_URL=postgres://user:password@postgres:5432/taca_ua
      - PYTHONUNBUFFERED=1
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
    depends_on:
      - rabbitmq
      - postgres
      - loki

  public-api:
    build:
      context: ./src/apis/public-api
      dockerfile: Dockerfile.dev
    volumes:
      - ./src/apis/public-api:/app
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=${RABBITMQ_USER:-guest}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD:-guest}
      - PYTHONUNBUFFERED=1
    depends_on:
      - rabbitmq
      - loki

# Microservices
  matches-service:
    build:
      context: ./src/microservices/matches-service
      dockerfile: Dockerfile.dev
    volumes:
      - ./src/microservices/matches-service:/app
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=${RABBITMQ_USER:-guest}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD:-guest}
      - PYTHONUNBUFFERED=1
    depends_on:
      - rabbitmq
      - loki

  modalities-service:
    build:
      context: ./src/microservices/modalities-service
      dockerfile: Dockerfile.dev
    volumes:
      - ./src/microservices/modalities-service:/app
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=${RABBITMQ_USER:-guest}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD:-guest}
      - PYTHONUNBUFFERED=1
    depends_on:
      - rabbitmq
      - loki

  ranking-service:
    build:
      context: ./src/microservices/ranking-service
      dockerfile: Dockerfile.dev
    volumes:
      - ./src/microservices/ranking-service:/app
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=${RABBITMQ_USER:-guest}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD:-guest}
      - PYTHONUNBUFFERED=1
    depends_on:
      - rabbitmq
      - loki

  read-model-updater:
    build:
      context: ./src/microservices/read-model-updater
      dockerfile: Dockerfile.dev
    volumes:
      - ./src/microservices/read-model-updater:/app
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=${RABBITMQ_USER:-guest}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD:-guest}
      - PYTHONUNBUFFERED=1
    depends_on:
      - rabbitmq
      - loki

  tournaments-service:
    build:
      context: ./src/microservices/tournaments-service
      dockerfile: Dockerfile.dev
    volumes:
      - ./src/microservices/tournaments-service:/app
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=${RABBITMQ_USER:-guest}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD:-guest}
      - PYTHONUNBUFFERED=1
    depends_on:
      - rabbitmq
      - loki

# Frontend Services
  admin-panel:
    build:
      context: ./src/frontend/admin-panel
      dockerfile: Dockerfile
    volumes:
      - ./src/frontend/admin-panel:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  public-website:
    build:
      context: ./src/frontend/public-website
      dockerfile: Dockerfile
    volumes:
      - ./src/frontend/public-website:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true


volumes:
  postgres_data:
  minio_data:
